(()=>{'use strict';
const app=document.getElementById('app');
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(text,url,secondary=false)=>'<a class="button '+(secondary?'secondary':'')+'" href="'+url+'">'+text+'</a>';
const steps=[
{title:'¿Qué equipo tienes?',help:'La orientación sirve para aparatos que ya no usas o que presentan fallas.',options:['Teléfono o tableta','Computador o periférico','Audio o video','Pequeño electrodoméstico','Otro aparato electrónico']},
{title:'¿Has notado alguna condición inusual?',help:'Responde con lo que ya sabes. No necesitas encenderlo ni desmontarlo.',options:['Sí: daño, hinchazón o calentamiento inusual','No he notado nada inusual','No estoy seguro']},
{title:'¿Conoces su funcionamiento?',help:'No hagas pruebas si desconoces su condición.',options:['Funciona','Presenta fallas','No lo sé']}
];let answers=[],step=0;
function show(html){app.innerHTML=html;app.classList.remove('screen-enter');void app.offsetWidth;app.classList.add('screen-enter');const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[step]=Number(b.dataset.answer);answers=answers.slice(0,step+1);if(step===1&&answers[1]!==1)result();else if(step===2)result();else{step++;question()}});app.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{if(step>0){step--;question()}else location.hash=''});}
function home(){show('<div class="eyebrow">Medellín · Tecnología con segunda vida</div><h1>Tu equipo todavía tiene un destino.</h1><p class="lead">Descubre cómo aprovecharlo o preparar una entrega responsable.</p><ol class="process"><li><strong>Conoce tus opciones</strong><span>Una orientación breve según su estado.</span></li><li><strong>Prepara tus equipos</strong><span>Reúne uno o varios en una entrega.</span></li><li><strong>Sigue la recepción</strong><span>Consulta tu código y su confirmación.</span></li></ol><div class="actions">'+link('Orientar mi decisión','#orientacion')+link('Entrar a mis entregas','entregas.html',true)+'</div><section class="split"><div><span class="eyebrow">Puntos de recolección</span><h2>Ubica una alternativa en la ciudad.</h2><p>Consulta el mapa y las condiciones de los puntos registrados.</p>'+link('Consultar mapa','mapa.html',true)+'</div><aside class="noki-note"><img src="noki-original.png" alt="Noki, la mascota del proyecto"><p>Noki nos recuerda que un aparato olvidado puede tener otra oportunidad.</p></aside></section><p class="muted">La orientación funciona sin conexión después de la primera carga. Las entregas compartidas y las rutas necesitan internet.</p>')}
function question(){const q=steps[step];show('<a href="index.html" class="text-link">Volver al inicio</a><div class="eyebrow">Orientación · Paso '+(step+1)+' de hasta 3</div><h1>'+q.title+'</h1><p>'+q.help+'</p><div class="choices">'+q.options.map((s,i)=>'<button class="secondary" data-answer="'+i+'">'+e(s)+'</button>').join('')+'</div><button class="quiet" data-back>Anterior</button>')}
function result(){const concern=answers[1]!==1,works=answers[2]===0;const title=concern?'Consulta su condición antes de entregarlo.':works?'Puede seguir siendo útil.':'Una revisión puede darle otra oportunidad.';const copy=concern?'Describe la condición al receptor y acuerda cómo llevarlo. No lo cargues ni lo desmontes si presenta daños o una batería hinchada.':works?'Considera conservarlo para una función útil o entregarlo a alguien que lo necesite. Antes de cederlo, protege tus datos y explica sus limitaciones.':'Consulta si conviene repararlo. Si eliges entregarlo para gestión como residuo, verifica que el punto reciba ese tipo de equipo.';show('<div class="eyebrow">Tu siguiente paso</div><h1>'+title+'</h1><p class="lead">'+copy+'</p><section><h2>¿Dónde quieres continuar?</h2><div class="actions">'+link('Preparar entrega académica','entregas.html')+link('Buscar un punto real','mapa.html',true)+'</div><p class="muted">La entrega académica genera un registro compartido con el profesor. Los puntos reales del mapa no reciben notificaciones de Noki.</p></section><details><summary>Revisar lo que respondiste</summary><ul>'+answers.map((a,i)=>'<li>'+e(steps[i].options[a])+'</li>').join('')+'</ul></details><div class="actions">'+link('Cambiar respuestas','#orientacion',true)+link('Terminar orientación','index.html',true)+'</div>')}
function route(){if(location.hash==='#orientacion'){step=0;answers=[];question()}else home()}
app.addEventListener('click',event=>{const anchor=event.target.closest('a[href="#orientacion"]');if(anchor&&location.hash==='#orientacion'){event.preventDefault();route()}});
window.addEventListener('hashchange',route);route();
})();
