(()=>{
 const points=[
 {name:'Centro de Acopio Ambiental Monterrey',lat:6.21431,lng:-75.57677,address:'Carrera 48 #10-45. Segundo piso, rampa de parqueaderos.',receives:'Aparatos eléctricos y electrónicos. Confirma las condiciones para tu equipo.',hours:'Horario publicado: 6:00 p. m. a 8:00 p. m.',phone:'+576046048912',source:'https://monterrey.com.co/_servicios/ambiental-monterrey/'},
 {name:'Recolección Respel El Tesoro',lat:6.1975427,lng:-75.5588351,address:'Carrera 25A #1A Sur-45. Ingreso por la transversal Superior, costado derecho de la vía interna.',receives:'Computación, telefonía, electrodomésticos, herramientas eléctricas, audio, video y baterías de celular.',hours:'Lunes a domingo, 7:00 a. m. a 9:00 p. m.',phone:'+576043211010',source:'https://eltesoro.com.co/servicios/recoleccion-respel/'}
 ];
 const status=document.querySelector('#map-status');let selected=0,map,line,originMarker,picking=false,requesting=false;
 function select(i){selected=i;const p=points[i];document.querySelector('#selected').innerHTML='<span class="eyebrow">Punto seleccionado</span><h2>'+p.name+'</h2><p>'+p.address+'</p><p>'+p.hours+'</p><div class="actions"><button id="route">Ruta en carro desde mi ubicación</button><a class="button secondary" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination='+p.lat+','+p.lng+'">Abrir navegación en Google Maps</a></div><p class="muted">Al calcular la ruta, el navegador pedirá ubicación y enviará el origen y destino al servicio OSRM. Noki no los guarda. Ruta estimada, sin tráfico en vivo.</p>';document.querySelector('#route').onclick=locate;if(map)map.panTo([p.lat,p.lng]);if(line){line.remove();line=null}status.textContent='';}
 if(window.L){map=L.map('map',{scrollWheelZoom:false}).setView([6.208,-75.569],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>status.textContent='El mapa no pudo cargar. Puedes consultar las direcciones de abajo.').addTo(map);points.forEach((p,i)=>L.circleMarker([p.lat,p.lng],{radius:12,color:'#ffffff',weight:3,fillColor:'#125e4e',fillOpacity:1}).addTo(map).bindTooltip(p.name).on('click',()=>select(i)));map.on('click',e=>{if(picking){picking=false;route(e.latlng.lat,e.latlng.lng)}})}
 else{document.querySelector('#map').textContent='Mapa no disponible. Consulta las fichas de los puntos.'}
 document.querySelector('#places').innerHTML=points.map((p,i)=>'<article><h2>'+p.name+'</h2><p>'+p.address+'</p><p>'+p.receives+'</p><p>'+p.hours+'</p><div class="actions"><button class="secondary" data-point="'+i+'">Seleccionar punto</button><a class="button secondary" href="tel:'+p.phone+'">Llamar</a><a class="text-link" target="_blank" rel="noopener" href="'+p.source+'">Fuente oficial</a></div></article>').join('');
 document.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.point));document.querySelector('#map').scrollIntoView({behavior:'smooth'})});
 document.querySelector('#pick-origin').onclick=()=>{if(!map)return;picking=true;status.textContent='Toca el mapa para elegir el origen. Se enviará al servicio de rutas OSRM.';document.querySelector('#map').scrollIntoView({behavior:'smooth'})};
 function locate(){if(requesting)return;if(!navigator.onLine){status.textContent='Conéctate a internet para calcular una ruta.';return}if(!navigator.geolocation){status.textContent='Tu navegador no ofrece ubicación. Marca un origen en el mapa.';return}status.textContent='Esperando permiso y ubicación…';requesting=true;navigator.geolocation.getCurrentPosition(pos=>{requesting=false;route(pos.coords.latitude,pos.coords.longitude)},()=>{requesting=false;status.textContent='No se obtuvo la ubicación. Puedes habilitarla o marcar el origen en el mapa.'},{timeout:12000,maximumAge:60000,enableHighAccuracy:false})}
 async function route(lat,lng){if(requesting||!map)return;requesting=true;const p=points[selected];status.textContent='Calculando ruta en carro…';try{const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+lng+','+lat+';'+p.lng+','+p.lat+'?overview=full&geometries=geojson',{signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok||result.code!=='Ok'||!result.routes.length)throw Error();const trip=result.routes[0];if(line)line.remove();if(originMarker)originMarker.remove();line=L.geoJSON(trip.geometry,{style:{color:'#2069c0',weight:5}}).addTo(map);originMarker=L.circleMarker([lat,lng],{radius:8,fillColor:'#2069c0',color:'white',fillOpacity:1}).addTo(map).bindTooltip('Origen');map.fitBounds(line.getBounds(),{padding:[24,24]});status.textContent='Ruta en carro: '+(trip.distance/1000).toFixed(1)+' km, aproximadamente '+Math.ceil(trip.duration/60)+' minutos. Sin tráfico en vivo.'}catch{status.textContent='El servicio no pudo calcular la ruta. Usa el botón de Google Maps como alternativa.'}finally{requesting=false}}
 select(0);
})();
