import * as api from './api.mjs';
const root=document.querySelector('#root'),notice=document.querySelector('#notice');
const categories=['Telefonía y tabletas','Computación','Audio y video','Accesorios y cables','Pequeños electrodomésticos','Otros equipos'];
const statuses={pending:'Pendiente de entrega',received:'Recibida',cancelled:'Cancelada',expired:'Vencida'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Bogota'}).format(new Date(s));
let data,view='home',busy=false,polling=false,draft,found;
const message=s=>notice.textContent=s;
function draftKey(){return 'noki-draft-'+api.user().id}
function getDraft(){try{draft=JSON.parse(localStorage.getItem(draftKey()))}catch{}draft ||= {request:crypto.randomUUID(),items:[{category:categories[0],description:'',quantity:1,condition:'unknown'}],slot:'',checks:[false,false]}}
function storeDraft(){try{localStorage.setItem(draftKey(),JSON.stringify(draft))}catch{message('Este navegador no pudo guardar el borrador. Mantén la página abierta.')}}
function render(html){root.innerHTML=html;root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));root.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();run(()=>submit(f))})}
async function run(fn){if(busy)return;busy=true;message('');root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){message(e.message)}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false)}}
function loginView(){render('<h1>Tu próxima entrega empieza aquí.</h1><p>Registra tus equipos y consulta su recepción. Usa el acceso individual que recibiste para la clase.</p><form class="login" id="login"><label>Usuario<input name="email" placeholder="estudiante01" autocomplete="username" required></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><button>Entrar</button></form><p>Necesitas internet para iniciar sesión y confirmar entregas.</p>')}
function nav(){return `<nav><button data-action="home" class="secondary">Mis entregas</button>${data.roles.length?'<button data-action="receiver" class="secondary">Recepción</button>':''}<button class="secondary" data-action="logout">Cerrar sesión</button></nav>`}
function mine(){return data.deliveries.filter(d=>d.user_id===api.user().id)}
function card(d){const s=data.slots.find(s=>s.id===d.slot_id),p=data.points.find(p=>p.id===d.point_id);return `<article><span class="badge">${statuses[d.status]}</span><h2>${esc(p?.name||'Punto registrado')}</h2><ul>${d.noki_items.map(i=>`<li>${i.quantity} × ${esc(i.description)} · ${esc(i.category)}</li>`).join('')}</ul>${s?`<p>Desde ${date(s.starts_at)} hasta ${date(s.ends_at)} (hora de Colombia).</p>`:''}<span class="code">${esc(d.code)}</span>${d.received_at?`<p>Recepción confirmada: ${date(d.received_at)}.</p>`:''}${d.status==='pending'&&d.user_id===api.user().id?`<div class="actions"><button data-action="copy:${d.id}" class="secondary">Copiar código</button><button data-action="cancel:${d.id}" class="secondary">Cancelar entrega</button></div>`:''}</article>`}
function home(){view='home';const pending=mine().find(d=>d.status==='pending');render(`${nav()}<h1>${pending?'Tu entrega está pendiente.':'Mis entregas'}</h1><p>${esc(api.user().email)} · Cada registro puede reunir varios equipos.</p>${pending?'<p>Conserva el código. La recepción se actualizará cuando el receptor la confirme.</p>'+card(pending):'<button data-action="new">Registrar equipos</button>'}<h2>Historial</h2>${mine().filter(d=>d.status!=='pending').map(card).join('')||'<p>Aún no tienes entregas cerradas.</p>'}`)}
function newDelivery(){view='draft';getDraft();const slots=data.slots.filter(s=>new Date(s.ends_at)>new Date());render(`${nav()}<h1>Prepara tu lote de equipos.</h1><p>Añade los aparatos, elige un horario y revisa tu entrega antes de confirmarla.</p><form id="delivery"><div id="items">${draft.items.map((i,n)=>`<section><h2>Equipo ${n+1}</h2><label>Categoría<select data-item="${n}" data-field="category">${categories.map(c=>`<option ${c===i.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Descripción<input data-item="${n}" data-field="description" value="${esc(i.description)}" required maxlength="120" placeholder="Ejemplo: portátil sin uso"></label><div class="grid"><label>Cantidad<input type="number" min="1" max="50" step="1" required data-item="${n}" data-field="quantity" value="${i.quantity}"></label><label>Estado<select data-item="${n}" data-field="condition">${[['works','Funciona'],['faults','Presenta fallas'],['unknown','No conozco su estado']].map(([v,l])=>`<option value="${v}" ${v===i.condition?'selected':''}>${l}</option>`).join('')}</select></label></div>${draft.items.length>1?`<button type="button" class="secondary" data-action="remove:${n}">Quitar este equipo</button>`:''}</section>`).join('')}</div><button type="button" class="secondary" data-action="add">Añadir otro equipo</button><section><label>Horario de entrega<select name="slot" required><option value="">Selecciona una franja</option>${slots.map(s=>`<option value="${s.id}" ${s.id===draft.slot?'selected':''}>${esc(data.points.find(p=>p.id===s.point_id)?.name)} · ${date(s.starts_at)} — ${date(s.ends_at)}</option>`).join('')}</select></label>${!slots.length?'<p>El receptor aún no ha establecido un horario vigente. Puedes conservar el borrador mientras lo prepara.</p>':''}<label class="check"><input type="checkbox" name="check0" ${draft.checks[0]?'checked':''} required>Revisé la protección de mis datos personales.</label><label class="check"><input type="checkbox" name="check1" ${draft.checks[1]?'checked':''} required>Confirmé cómo llevar los equipos, sin desmontarlos.</label></section><button>Revisar entrega</button></form>`);
root.querySelector('#delivery').oninput=e=>{const t=e.target;if(t.dataset.item!==undefined)draft.items[Number(t.dataset.item)][t.dataset.field]=t.dataset.field==='quantity'?Number(t.value):t.value;if(t.name==='slot')draft.slot=t.value;if(t.name.startsWith('check'))draft.checks[Number(t.name.slice(-1))]=t.checked;storeDraft()}}
function review(){view='review';const s=data.slots.find(s=>s.id===draft.slot);render(`${nav()}<h1>Revisa antes de confirmar.</h1><section><ul>${draft.items.map(i=>`<li>${i.quantity} × ${esc(i.description)} · ${esc(i.category)}</li>`).join('')}</ul><p>${esc(data.points.find(p=>p.id===s.point_id)?.name)}</p><p>${date(s.starts_at)} — ${date(s.ends_at)} (Colombia).</p><p>Se generará un único código para este lote. No podrás crear otra entrega mientras esté pendiente.</p></section><div class="actions"><button data-action="confirm">Confirmar y generar código</button><button class="secondary" data-action="new">Corregir datos</button></div>`)}
function receiver(){view='receiver';render(`${nav()}<h1>Recepción académica</h1><form id="lookup"><label>Código de entrega<input name="code" required placeholder="Pega o escribe el código completo" autocomplete="off"></label><button>Buscar entrega</button></form>${found?card(found)+(found.status==='pending'?'<p>Confirma solo cuando hayas recibido todos los equipos del lote.</p><button data-action="receive">Confirmar recepción completa</button>':''):''}<details><summary>Establecer horario de la demostración</summary><form id="slot"><label>Punto<select name="point">${data.points.filter(p=>data.roles.some(r=>r.point_id===p.id)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Desde (hora de Colombia)<input name="start" type="datetime-local" required></label><label>Hasta (hora de Colombia)<input name="end" type="datetime-local" required></label><button>Guardar horario</button></form></details>`)}
async function submit(form){const f=new FormData(form);if(form.id==='login'){let email=f.get('email').trim();if(!email.includes('@'))email+='@noki.example';await api.login(email,f.get('password'));form.reset();data=await api.snapshot();home()}if(form.id==='delivery'){storeDraft();review()}if(form.id==='lookup'){await refresh(false);found=data.deliveries.find(d=>d.code===f.get('code').trim()&&data.roles.some(r=>r.point_id===d.point_id));receiver();if(!found)message('Código no encontrado en tus puntos autorizados.')}if(form.id==='slot'){await api.rpc('noki_create_slot',{p_point:f.get('point'),p_start:f.get('start')+':00-05:00',p_end:f.get('end')+':00-05:00'});await refresh(false);receiver();message('Horario guardado. Los estudiantes ya pueden elegirlo.')}}
async function refresh(draw=true){data=await api.snapshot();if(draw&&view==='home')home();if(draw&&view==='receiver'){if(found)found=data.deliveries.find(d=>d.id===found.id);receiver()}}
function action(value){return run(async()=>{const[a,id]=value.split(':');if(a==='logout'){await api.logout();data=null;draft=null;found=null;loginView()}if(a==='home'){await refresh(false);home()}if(a==='new'){if(mine().some(d=>d.status==='pending'))home();else newDelivery()}if(a==='receiver'){found=null;await refresh(false);receiver()}if(a==='add'){if(draft.items.length>=20)throw new Error('Puedes añadir hasta 20 líneas.');draft.items.push({category:categories[0],description:'',quantity:1,condition:'unknown'});storeDraft();newDelivery()}if(a==='remove'){draft.items.splice(Number(id),1);storeDraft();newDelivery()}if(a==='confirm'){await api.rpc('noki_create_delivery',{p_request:draft.request,p_slot:draft.slot,p_items:draft.items});try{localStorage.removeItem(draftKey())}catch{}draft=null;await refresh(false);home();message('Entrega registrada. Conserva tu código.')}if(a==='cancel'){if(!confirm('¿Cancelar esta entrega? Quedará en tu historial y podrás crear otra.'))return;await api.rpc('noki_cancel_delivery',{p_id:id});await refresh(false);home()}if(a==='copy'){const d=mine().find(d=>d.id===id);try{await navigator.clipboard.writeText(d.code);message('Código copiado.')}catch{message('Selecciona el código y cópialo manualmente.')}}if(a==='receive'){const d=await api.rpc('noki_receive_delivery',{p_code:found.code});await refresh(false);found=data.deliveries.find(x=>x.id===d.id);receiver();message(d.status==='received'?'Recepción confirmada.':'La entrega venció y no se registró como recibida.')}})}
async function poll(){if(polling||busy||!api.user()||document.hidden||view!=='home')return;polling=true;try{await refresh()}catch(e){message('No se pudo actualizar el estado: '+e.message)}finally{polling=false}}
setInterval(poll,10000);window.addEventListener('online',poll);document.addEventListener('visibilitychange',poll);
if(api.user()){run(async()=>{data=await api.snapshot();home()}).then(()=>{if(!data)loginView()})}else loginView();
